default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: xxlkiclodsocyg
#  username: bookshare
  password: a8c206d2359b50de7a73e0a5dcd5484217ec42db8b93c24a7cd01e55c80447ee
#  password: bookshare
  host:     ec2-54-235-153-124.compute-1.amazonaws.com
#  host:     localhost
  port: 5432

development:
  <<: *default
  database: deskpquhflmrs7
#  database: bookshare

#test:
#  <<: *default
#  database: BookShare_test

production:
  <<: *default
  database: BookShare_Backend_production