default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: BookShare_development

test:
  <<: *default
  database: BookShare_test

production:
  <<: *default
  database: BookShare_Backend_production